# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./qt_draw_xy.h
SOURCES += ./qt_draw_xy.cpp \
    ./main.cpp
FORMS += ./qt_draw_xy.ui
RESOURCES += qt_draw_xy.qrc
